package com.example.report.entity;

import com.sh.base.entity.BaseEntity;

public class ResumeCheckEntity extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internalrecommendation_share.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internalrecommendation_share.Reference
     *
     * @mbggenerated
     */
    private Integer reference;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internalrecommendation_share.isFirst
     *
     * @mbggenerated
     */
    private Integer visits;

    private Integer isrewarded;

    private Integer attribution;

    public Integer getAttribution() {
        return attribution;
    }

    public void setAttribution(Integer attribution) {
        this.attribution = attribution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internalrecommendation_share.id
     *
     * @return the value of internalrecommendation_share.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internalrecommendation_share.id
     *
     * @param id the value for internalrecommendation_share.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internalrecommendation_share.Reference
     *
     * @return the value of internalrecommendation_share.Reference
     *
     * @mbggenerated
     */
    public Integer getReference() {
        return reference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internalrecommendation_share.Reference
     *
     * @param reference the value for internalrecommendation_share.Reference
     *
     * @mbggenerated
     */
    public void setReference(Integer reference) {
        this.reference = reference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internalrecommendation_share.isFirst
     *
     * @return the value of internalrecommendation_share.isFirst
     *
     * @mbggenerated
     */
    public Integer getVisits() {
        return visits;
    }

    public void setVisits(Integer visits) {
        this.visits = visits;
    }

    public Integer getIsrewarded() {
        return isrewarded;
    }

    public void setIsrewarded(Integer isrewarded) {
        this.isrewarded = isrewarded;
    }
}