package com.example.report.dao;

import com.example.report.entity.ResumeCheckEntity;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.HashMap;
import java.util.List;

@Repository
@Mapper
public interface ResumeCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internalrecommendation_share
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internalrecommendation_share
     *
     * @mbggenerated
     */
    int insert(ResumeCheckEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internalrecommendation_share
     *
     * @mbggenerated
     */
    int insertSelective(ResumeCheckEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internalrecommendation_share
     *
     * @mbggenerated
     */
    ResumeCheckEntity selectByReference(Integer reference);

    List<ResumeCheckEntity> selectByEntity(ResumeCheckEntity entity);

    List<ResumeCheckEntity> selectByMap(HashMap<String, Object> map);

    Integer selectCountByMap(HashMap<String, Object> map);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internalrecommendation_share
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ResumeCheckEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internalrecommendation_share
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ResumeCheckEntity record);
}