package com.example.report.service;

import com.example.report.entity.ResumeCheckEntity;
import com.sh.base.page.PageBean;

import java.util.List;

public interface ResumeCheckService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internalrecommendation_share
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internalrecommendation_share
     *
     * @mbggenerated
     */
    int insert(ResumeCheckEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internalrecommendation_share
     *
     * @mbggenerated
     */
    int insertSelective(ResumeCheckEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internalrecommendation_share
     *
     * @mbggenerated
     */
    ResumeCheckEntity selectByReference(Integer reference);

    List<ResumeCheckEntity> selectByEntity(ResumeCheckEntity entity);

    PageBean selectPageByEntity(ResumeCheckEntity entity) throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internalrecommendation_share
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ResumeCheckEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table internalrecommendation_share
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ResumeCheckEntity record);


}
