package com.example.report.form;

import com.example.report.entity.ResumeCheckEntity;
import com.sh.base.form.BaseForm;

public class ResumeCheckForm extends BaseForm<ResumeCheckEntity> {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internalrecommendation_share.Reference
     *
     * @mbggenerated
     */
    private Integer reference;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column internalrecommendation_share.isFirst
     *
     * @mbggenerated
     */
    private Integer visits;

    private Integer isrewarded;

    private Integer attribution;

    public Integer getAttribution() {
        return attribution;
    }

    public void setAttribution(Integer attribution) {
        this.attribution = attribution;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internalrecommendation_share.Reference
     *
     * @return the value of internalrecommendation_share.Reference
     *
     * @mbggenerated
     */
    public Integer getReference() {
        return reference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column internalrecommendation_share.Reference
     *
     * @param reference the value for internalrecommendation_share.Reference
     *
     * @mbggenerated
     */
    public void setReference(Integer reference) {
        this.reference = reference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column internalrecommendation_share.isFirst
     *
     * @return the value of internalrecommendation_share.isFirst
     *
     * @mbggenerated
     */
    public Integer getVisits() {
        return visits;
    }

    public void setVisits(Integer visits) {
        this.visits = visits;
    }

    public Integer getIsrewarded() {
        return isrewarded;
    }

    public void setIsrewarded(Integer isrewarded) {
        this.isrewarded = isrewarded;
    }

    @Override
    public void FormToEntity(ResumeCheckEntity entity) throws Exception {
        super.FormToEntity(entity);
        entity.setVisits(this.getVisits());
        entity.setIsrewarded(this.getIsrewarded());
        entity.setAttribution(this.getAttribution());
        entity.setReference(this.getReference());
    }

    @Override
    public void EntityToForm(ResumeCheckEntity entity) throws Exception {
        super.EntityToForm(entity);
    }
}
